server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_security?useSSL=false&&useUnicode=true&&characterEncoding=UTF-8&&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.wang.pojo
  mapper-locations: classpath:com/wang/mapper/*.xml

